/**************************************************************************/
/*  Licensed Materials - Property of IBM                                  */
/*  (C) Copyright IBM Corporation 2003, 2004.                             */
/*  All rights reserved.                                                  */		
/*                                                                        */
/* US Government Users Restricted Rights - Use, duplication or            */
/* disclosure restricted by GSA ADP Schedule Contract with                */
/* IBM Corporation.                                                       */
/**************************************************************************/
/*  Permission Notice                                                     */
/*                                                                        */
/*  Permission is granted to copy, use, modify, and merge this sample     */
/*  software into your applications and to permit others to do any of the */
/*  foregoing. You may further distribute this software for               */
/*  commercial purposes only as part of your application that adds        */
/*  significant value and function beyond that provided by these          */
/*  samples.                                                              */
/*  You must include this permission statement and retain the copyright   */
/*  notice in all copies and modified versions of this software.          */
/*                                                                        */
/**************************************************************************/
/*                                                                        */
/*  DISCLAIMER OF WARRANTIES                                              */
/*                                                                        */
/*  The sample software is provided to you by IBM to assist you in        */
/*  developing your applications. THIS SOFTWARE IS PROVIDED AS-IS,        */
/*  WITHOUT WARRANTY OF ANY KIND. IBM SHALL NOT BE LIABLE FOR ANY         */
/*  DAMAGES ARISING OUT OF YOUR USE OR THE USE BY ANY THIRD PARTY OF      */
/*  OF THE SAMPLE SOFTWARE EVEN IF IT HAS BEEN ADVISED OF THE POSSIBILITY */
/*  OF SUCH DAMAGES. IN ADDITION, IBM SHALL NOT BE LIABLE FOR ANY THIRD   */
/*  PARTY CLAIMS AGAINST YOU.                                             */
/*                                                                        */
/**************************************************************************/
/* Generated by JCasGen Wed May 05 14:41:10 EDT 2004*/

package org.codehaus.faqbot.annotator;

import com.ibm.uima.jcas.tcas.Annotation;
import com.ibm.uima.jcas.impl.JCas;
import com.ibm.uima.jcas.cas.TOP_Type;

public class Sentence extends Annotation {

  public final static int typeIndexID = JCas.getNextIndex();
  public final static int type = typeIndexID;
  public           int getTypeIndexID() {return typeIndexID;}

  // Never called.  Disable default constructor
  protected Sentence() {}

  /** Internal - Constructor used by generator */
  public Sentence(int addr, TOP_Type type) {
    super(addr, type);
  }

  public Sentence(JCas jcas) {
    super(jcas);
  }


    public Sentence(JCas jcas, int start, int end) { super(jcas, start, end);}
}
